### ISSUE TITLE
Remove spectator free-cam scroll wheel modifier

### ISSUE THREAD

**Issue by Sniperhid** [TMF3/TMF#10]
Whilst a neat concept. I think scrollwheel is much better suited to being used to shift the camera position closer/further to the camera focal point. In its place we could add more modifier keys for the speed with alt also playing a part. This would could look something like below.

- No key - This should be a reasonable speed
- Shift pressed - Speed boost - State 1
- Alt pressed - Speed boost - State 2
- Alt+shift pressed - Speed boost - State 3
- Ctrl - Slow speed? - Though maybe don't use.

**Comment by headswe** [comment]
#36abbdb

**Comment by headswe** [comment]
I think ctrl and shift will be enough.

**Comment by Sniperhid** [comment]
More tweaks in https://github.com/TMF3/TMF/commit/8c9cd9cba197d3416005e0b4f2ecb7c0ff0c65d8
