### ISSUE TITLE
Garrison module - save a list of units

### ISSUE THREAD

**Issue by Boberro** [TMF3/TMF#126]
Garrison module should keep a list of created units somewhere. Either a variable on the logic or a global variable named in a text field in logic's attributes. If it's a namespace variable, it's name should be mentioned somewhere in a module

**Comment by Sniperhid** [comment]
What about using `synchronizeObjectsAdd` to synchronize them back to the module so `synchronizedObjects _module` would return the units?

**Comment by Boberro** [comment]
And then check if they're not HC or some other module that can be used sometime in the future?
