### ISSUE TITLE
Supporting features for admin menu

### ISSUE THREAD

**Issue by beaar** [TMF3/TMF#144]
- [x] **Store extra player data in spectator unit on death**
Supporting a quick respawn feature, the following information should be available:
- TMF loadout and role
- Group
- Side (`side oldGroup` ^ ?)
- Position of death
- Vehicle (if not on foot)

The presence or absence of this information determines whether the quick respawn button will be displayed in the player list.

- [x] **Ability to toggle Safe Start on/off indefinitely**
There should exist a getter as well.

- [ ] **Extension for retrieving system time**
Important for the admin log/message tab mainly. Should be for #139 as well.

**Comment by headswe** [comment]
@beaar can you look this over and see if we can close it?
