### ISSUE TITLE
[BUG] TMF Garrison used with Units not originally of side causes Murderisation

### ISSUE THREAD

**Issue by Commander-Teizan** [TMF3/TMF#166]
Basically, when you make Opfor units Blufor (through grouping and then ungrouping them from a Blufor), and then sync them to the TMF Garrison, come playtest they murderise eachother. Quite interesting, but unintended.

**Comment by cptnnick** [comment]
Do they all become hostile to each other or do they revert to their opfor side and engage other blufor units?

**Comment by Commander-Teizan** [comment]
I checked over them in Spectator: They remain Blufor, and they start murdering eachother.
