### ISSUE TITLE
Wave Spawner - Wave spawned aircraft fall out of the sky

### ISSUE THREAD

**Issue by Samjm850** [TMF3/TMF#167]
If you sync the wave spawner to an aircraft, the aircraft will fall straight down as soon as it spawns. Including if you use flyInHeight. (Also tested without wave spawner to double check and it worked fine if the aircraft was there at mission start).

In the case of the F35B I used recently, the ejector seat spawned in mid air at mission start and fell to the ground. The plane would then spawn in when the trigger was activated but with no pilot.

**Comment by notsewtrebor** [comment]
Have had a similar issue. I set an AN-2 to paradrop troops in a certain location, worked fine. Linked it to a wavespawner and the plane drops out of the sky.
