### ISSUE TITLE
ACE+TMF marker incompatibility

### ISSUE THREAD

**Issue by cptnnick** [TMF3/TMF#17]
> Both ACE and TMF work fine independantly though, so it can't just be a problem with ACE

**Comment by paullee18** [comment]
To elaborate, the marker placing UI does not appear correctly on the screen and when you do manage to put down a marker it will adjust itself to a different position.

**Comment by Sniperhid** [comment]
We'll look into the cause, temporary solution is to pull ace_markers which we are doing at 1Tac as we distribute our version of ACE. We will look into fixing this though as this isn't a suitable permeant solution.

**Comment by Sniperhid** [comment]
Fixed in https://github.com/TMF3/TMF/commit/147111804fbce21d57a7323c6808b0bcef826118

That was annoying to find and fix.
