### ISSUE TITLE
Autotest doesn't take into account radio assignment.

### ISSUE THREAD

**Issue by ryanparsons7** [TMF3/TMF#176]
When running the autotest to ensure that no-one will run out of inventory space, radios that get assigned to not get taken into account, this makes some roles not having enough space for a 117F etc.

**Comment by Sniperhid** [comment]
Just a heads up autotest doesn't currently actually take into account whether items actually fit in inventory. Have made it so in the PR but I will work on the ACRE stuff as well as it's quite a common mission problem.

**Comment by Sniperhid** [comment]
Resolved by #180
