### ISSUE TITLE
Wave spawner units move towards [0,0,0]

### ISSUE THREAD

**Issue by Sniperhid** [TMF3/TMF#177]
This bug has happened a few times where **some** units that are spawned in will start moving towards [0,0,0] it has occured in a few missions.

Exhibit one -> http://1tac.tk/r3/share/25
At 20:44 you can see at least one group has left the AO to the south west. Note around 23:00 the host activated a hunt script to fix the issue.

**Comment by headswe** [comment]
I need to sit down and try and replicate this.
