### ISSUE TITLE
ACE Medical Menu Broken When Using TMF + ACE

### ISSUE THREAD

**Issue by paullee18** [TMF3/TMF#18]
To reproduce:

Enable at least TMF and ACE3, proceed to go in game and bring up the ACE Medical Menu (Default key H). Menu should be unresponsive and not let you even inject morphine. It also shows Advanced Medical tabs even if the mission is set to basic (These are usually greyed out).

**Comment by Sniperhid** [comment]
Perhaps https://github.com/TMF3/TMF/commit/147111804fbce21d57a7323c6808b0bcef826118 fixed this?

**Comment by Sniperhid** [comment]
I am pretty confident that fixed the issue there. If not re-open the ticket.
