### ISSUE TITLE
AI Hunt and Wave Spawn Module Conflict

### ISSUE THREAD

**Issue by ryanparsons7** [TMF3/TMF#182]
Sync a opfor group via the leader to wave spawner that is **not** activated at start, spawn AI hunt modue with hunters set as opfor (enables at start), when mission starts the leader of the group gets cached but the rest of his group gets spawned in as normal.

Removing the AI hunt module fixes the issue and the entire group gets cached.

**Comment by headswe** [comment]
Can't mix AI hunt and Wave spawn modules, use the EH to call the hunt script on spawned AI.
