### ISSUE TITLE
JIP into unit that moved groups

### ISSUE THREAD

**Issue by Sniperhid** [TMF3/TMF#19]
May have been a one off but Sokka rejoined the server into an AI slot he previously occupied and was greeted with this -> http://images.akamai.steamusercontent.com/ugc/254842804695072177/8301531029F8212C043DD6365BF4E5B5D9BF61CA/ 
Not sure if this was an isolated incident, and no clue what's going on but just logging it for now.

This will happen under either of the following conditions:
- Joining onto a dead unit (Unit is killed during player loading)
- Unit has moved to another group.

Update since #175 - In both cases units will go into TMF spectator.

**Comment by headswe** [comment]
This happend back in A2 as well.

**Comment by Sniperhid** [comment]
`showCinemaBorder` Creates the border effect above - Perhaps what's neccesary is adding logic for killing a camera of sorts.

**Comment by Sniperhid** [comment]
Had this happen to me again this evening (crashed and rejoin my slot but it died)
Running the following from console put me right.
```sqf
showCinemaBorder false;
[player,player,true] spawn tmf_spectator_fnc_init;
```

**Comment by Sniperhid** [comment]
The above PR will now put the player into spectator. I think there is a way we can get the rejoining player back into the unit. The handleDisconnect event could store some info and we could check for it on JIP.
