### ISSUE TITLE
Admin ids kept as code variable are bad

### ISSUE THREAD

**Issue by Boberro** [TMF3/TMF#191]
Currently, admin ids are being kept in config.cpp, which server admin is supposed edit. This will lead to merge conflicts each time you're pulling new code.

It is suggested to keep admin ids (including ids of tmf devs :) ) in external config pbo.
Example (provided by Head):

    class CfgTmfAdminUsers {
        class Head {
            uid = 4304323434
        };
        class Bobbero {
            uid = 4040404
        }
    };

**Comment by beaar** [comment]
agreed

**Comment by PabstMirror** [comment]
Could use `#include "Admin_IDs_Devs.hpp"`
and then custom versions would just change that line to `#include "Admin_IDs_myGroup.hpp"`

`Devs.hpp` could change on master
and `mygroup.hpp` can change on fork without causing merge conflicts

**Comment by headswe** [comment]
Includes are a security risk and cause crashes if they don't exist.

**Comment by PabstMirror** [comment]
not userconfig, this would be compiled into the pbo

**Comment by headswe** [comment]
I would rather not need users to fuck around with TMF files.

When the config idea, coupled with an additional pbo would be nicer.

![image](https://user-images.githubusercontent.com/425212/33735812-b1fecd54-db90-11e7-9f93-9e1817c7da8f.png)
Config get merged -> output is both sam and head
make a small web app to make pbo for people like this, even better

Boom everything is cool and easy.

**Comment by beaar** [comment]
I'll leave the entries empty in the future, so it'll be up to each community to patch or fork with their own entries. I'll also change it to use classes.

**Comment by beaar** [comment]
It works this way on the adminmenu branch now

**Comment by Sniperhid** [comment]
We'll be aiming to merge the adminmenu into master soon :tm:
