### ISSUE TITLE
TMF Autotest displays faulty Missing Classname

### ISSUE THREAD

**Issue by AVESUM** [TMF3/TMF#202]
When equipping players inventory with goggles in loadout (in my case "G_Combat", tried with Tactical and Aviators aswell) TMF Autotest return "Missing classname: G_Combat (for:...)" on equipped players. Loadout is nevertheless successful. 

Snippet of loadout: 
    backpackItems[] = {
		"SAM_HelmetIA_M90",
		"G_Combat",
		"rhsusf_ANPVS_15",
		"ACE_CableTie",
		"ACE_key_lockpick"	
    };

**Comment by cptnnick** [comment]
What kind of item is "G_Combat"?

**Comment by AVESUM** [comment]
Goggles/eyewear but in my case I didn't equip them, just put them in the backback. Hope that answers the question.

**Comment by cptnnick** [comment]
Thank you, that helped. 

Currently (https://github.com/TMF3/TMF/blob/master/addons/autotest/functions/fn_testGear.sqf#L101) we only check backpackitems against cfgWeapons and cfgMagazines. To solve this error, we would have to check against cfgGlasses as well.

@Sniperhid this is your component originally, but ill be touching this bit when I finish faces next week. Want me to handle this when I'm doing that?
