### ISSUE TITLE
Add option to force-add radios

### ISSUE THREAD

**Issue by Freddo3000** [TMF3/TMF#206]
There are certain radio backpacks from mods such as IFA3 and Faces of War that add radio backpacks, however they often cannot fit manpac radios such as the AN/PRC-117 and AN/PRC-77.

As a solution to this, adding a checkbox option to force-add the items to backpack would solve it until there is proper support for backpack radios.

**Comment by Drofseh** [comment]
IFA3 has a some extra radio backpack classes that are large enough to carry ACRE radios.
```
B_LIB_GER_Radio_ACRE2
B_LIB_SOV_RA_Radio_ACRE2
B_LIB_US_Radio_ACRE2
```
They are set to `scope=1 ` though so they don't appear in the arsenal and must be added with a script.

**Comment by Freddo3000** [comment]
Huh, that I did not know. Does FoW have something similar?

**Comment by Drofseh** [comment]
I'm afraid I can't remember off the top of my head, easy enough to look in the config viewer though.
