### ISSUE TITLE
Add the ability to define ACE roles in TMF loadouts

### ISSUE THREAD

**Issue by Freddo3000** [TMF3/TMF#217]
So add the following:

- Medical (Medic, Doctor, etc)
- Engineer status (explosive specialist, engineer, etc)
- UAV hacker(?)

**Comment by beaar** [comment]
Could just use vanilla traits https://community.bistudio.com/wiki/setUnitTrait

**Comment by Freddo3000** [comment]
@beaar That is a solution, though it is not uncommon that that is forgotten, leaving medics unable to administer blood or engineers unable to repair. Having it integrated into the loadout removes that possibility.

Then again, you could have it in the code field, though that would be a less than optimal solution.

**Comment by headswe** [comment]
While the feature exist in vanilla, it wouldn't be a bad idea to extend it to the loadouts using the vanilla functions

**Comment by beaar** [comment]
I only meant to suggest using the vanilla traits instead of ACE ones. I wasn't shooting down the suggestion
