### ISSUE TITLE
"Create loadout page" needs to be rechecked in settings

### ISSUE THREAD

**Issue by Freddo3000** [TMF3/TMF#220]
"Create loadout page" in the TMF Briefing settings needs to be turned off and on before registering as being on, and therefore generating a loadout page. It currently defaults to on, but if you do not recheck it it does not generate a loadout page.

**Comment by headswe** [comment]
So what you are saying its, the default value is off but the checkbox indicates the default value is on.

**Comment by Freddo3000** [comment]
That is a much better way to put it.
