### ISSUE TITLE
AI synced to a garrison module still exists on the map when using a trigger

### ISSUE THREAD

**Issue by electronstorm** [TMF3/TMF#236]
All of the AI that is synched to a garrison module remains on the map until the trigger synched to the garrison module is activated. This kind of negates the point of using a trigger in the first place as there is still a ton of AI on the map. Once the trigger activates, the AI disappears and is replaced with the new garrison units as it should. 

Steps to replicate:
Place garrison module
Sync units to garrison module
Sync trigger to garrison module (in a way that it doesn't activate right away)
Preview result in the editor with the trigger not activated

Screenshots:
Editor: https://i.imgur.com/a1O4P6V.jpg
Trigger not active: https://i.imgur.com/3BXVdH3.jpg
Trigger active: https://i.imgur.com/tzSJKlU.jpg

**Comment by headswe** [comment]
Ah, yes I noticed this as well but forgot to report it!
Thanks for reporting and il look into it this weekend.

**Comment by Sniperhid** [comment]
Resolved in #241
