### ISSUE TITLE
Make fn_testGear more verbose

### ISSUE THREAD

**Issue by Freddo3000** [TMF3/TMF#253]
https://github.com/TMF3/TMF/blob/b74aaba26be5befa961a56a70adf2e305c9e23d0/addons/autotest/functions/fn_testGear.sqf#L16-L26

Adding a hint as to what type of item a class is would be nice.

### Possible solution:
Add additonal param e.g ["_subarray","_config","_itemType"] that contains a string describing what type of item is having an issue, such as "weapon". This making the output "Missing weapon classname: 'xyz'"

**Comment by beaar** [comment]
I don't think this is necessary. If it's not obvious from the classname itself (they're usually somewhat self-descriptive) then it should be from where it's used.
