### ISSUE TITLE
Use CBA group name in lobby instead of TMF

### ISSUE THREAD

**Issue by Freddo3000** [TMF3/TMF#262]
https://github.com/CBATeam/CBA_A3/wiki/Name-Groups-in-Lobby

Considering that TMF has CBA has a dependency, I don't see any reason for having duplicate functionality. CBA has also in my opinion a better implementation where it can be used for single-unit groups (such as CAS pilots).

It also fixes an issue I've been having sometimes, where in examples such as this:
> US Platoon Leader
> US Platoon Sergeant
> US Platoon Medic

Where it would cut out the `platoon` part.

This may have some issues with backwards compatibility, but in my opinion they aren't severe.

**Comment by Sniperhid** [comment]
Just spoke to Freddo on TS - He has tested the behaviour. If both a prefix and @ are present. both the end and the prefix are removed in the group name. A simple fix here would be to modify TMF to search for `@` and simply do nothing if that is detected.
