### ISSUE TITLE
Global Mobilization Gas Masks call errors in Autotest when added to Items - works correctly anyway.

### ISSUE THREAD

**Issue by CDRTeizan** [TMF3/TMF#280]
I include a Gas Mask in this:

>     items[] = {
>         LIST_10("ACE_fieldDressing"),
>         LIST_3("ACE_morphine"),
>         LIST_1("ACE_epinephrine"),
> 		LIST_1("ACE_CableTie"),
> 		"ACE_Earplugs","gm_gc_army_facewear_schm41m","ACE_Flashlight_KSF1","gm_pl_army_headgear_cap_80_moro","gm_bayonet_6x3_wud"
>     };

and it causes Havoc in Autotest like so:
![20191213132410_1](https://user-images.githubusercontent.com/31879365/70759711-2aed5a00-1dac-11ea-87fa-601222f25f00.jpg)
However, in testing, all is well regardless:
![20191213132903_1](https://user-images.githubusercontent.com/31879365/70759897-bd8df900-1dac-11ea-91dd-03bffc696132.jpg)
So basically, just Autotest calling a false positive.

**Comment by Freddo3000** [comment]
Has to do with autotest not checking for items in cfgGoggles I would assume.
