### ISSUE TITLE
Waypoint activation code is never executed for wave-spawned units

### ISSUE THREAD

**Issue by Plankton555** [TMF3/TMF#331]
Any code in the "on activation" field of a waypoint belonging to a wave-spawned unit is never executed. My guess is that the information is never saved/cached by the wavespawner module, and so is never reapplied on the respawned units (not even the first one).

**To reproduce**
Place a unit. Give it a waypoint. In the "On activation field", write e.g. `hint "REACHED WAYPOINT";`. Test it and verify that the text is displayed.
Now, connect the unit to a wave spawner. The text is now never displayed when the unit reaches the waypoint.

**Comment by Freddo3000** [comment]
Bear also noted that waypoint activation distance is not kept either.  

---
https://community.bistudio.com/wiki/setWaypointStatements  
https://community.bistudio.com/wiki/waypointStatements  
https://community.bistudio.com/wiki/setWaypointCompletionRadius  
https://community.bistudio.com/wiki/waypointCompletionRadius
