### ISSUE TITLE
Players randomly kicked to spectator, JIP involvement

### ISSUE THREAD

**Issue by Savolainen5** [TMF3/TMF#341]
Message appeared on screen about players JIPing and being forced to spectator, despite the TMF add-on configuration about JIP being allowed even after safestart is over. In the course of about an hour it happened to three players who were doing nothing out of the ordinary.

No ACRE, MP respawn settings allowed Respawn on Custom Position and Select Respawn Position but also had the TMF Spectator box ticked (possibly part of the problem?).

Apologies for the rather vague report.

**Comment by Sniperhid** [comment]
Resolved by #343
