### ISSUE TITLE
Headgear not assigning to units in custom loadouts

### ISSUE THREAD

**Issue by Savolainen5** [TMF3/TMF#344]
Headgear is not properly applied even to the rifleman class (which would probably then spread through the loadout chain) despite being in the same format as other "clothing" type items. Magazines and Items apply properly through the chain, so to the best of my knowledge, this applies only to headgear.

My custom loadout: https://cdn.discordapp.com/attachments/267832683583766528/729698824410366062/us_army_oefcp.hpp

**Comment by headswe** [comment]
This issue only occurred on the recently updated steam workshop item, correct?

**Comment by Savolainen5** [comment]
Correct. I did not try it on previous versions.

**Comment by Savolainen5** [comment]
Issue solved. Error was between the keyboard and the chair, not in the code. I missed a crucial part of the code of the items.
