### ISSUE TITLE
Jip units arent deleted when sent to spectator

### ISSUE THREAD

**Issue by headswe** [TMF3/TMF#362]

**Comment by Freddo3000** [comment]
https://github.com/TMF3/TMF/blob/768fb9433d208e35c4f634a8c9d3d4f70e779f9e/addons/spectator/XEH_clientPostInit.sqf#L26-L35

**Comment by headswe** [comment]
Thanks for the code or something, I observed this last night

Do I need to specify that its a bug report or do you wanna paste more code?

**Comment by Freddo3000** [comment]
I just pasted the thing that normally handles it. If you have any clue how to work around it then please do tell, do I need to add an additional delay on it?
