### ISSUE TITLE
Jipping into AI slot dosen't work

### ISSUE THREAD

**Issue by headswe** [TMF3/TMF#366]
What should happen:
Player should take control of the unit in question.

What happens:
Player briefly take control of the unit
The player is moved to spectator, camera is at 0,0,0

**Comment by Freddo3000** [comment]
I suppose https://github.com/TMF3/TMF/pull/343 didn't fix it then

**Comment by Freddo3000** [comment]
https://github.com/TMF3/TMF/blob/4fcb4e5ac9394101ad6f2c84fdb603725d7d6bb7/addons/spectator/XEH_clientPostInit.sqf#L23

logic error

**Comment by Freddo3000** [comment]
Maybe instead of setting it as a unit variable, store it as a global array and wait until it is synced?

**Comment by Sniperhid** [comment]
Fixed by #367
