### ISSUE TITLE
Wave spawner configurable start delay

### ISSUE THREAD

**Issue by VBingley** [TMF3/TMF#38]
As a mission maker I want a configurable start delay so waves begin at a certain time after mission start or I can sync multiple wave spawn modules to a single trigger and have them start at different times.

**Comment by headswe** [comment]
I use a trigger with the condition (time > XXX)

**Comment by Sniperhid** [comment]
Perhaps we could add a wait option - This could be wait X after trigger is triggered or wait X after mission start (if no trigger present)? Default value 0.

**Comment by headswe** [comment]
Why do?, it works fine with a trigger?
