### ISSUE TITLE
Not all garrison states reset properly when new missions are loaded

### ISSUE THREAD

**Issue by cptnnick** [TMF3/TMF#42]
Reset inside common\fn_edenInit.sqf

**Comment by Sniperhid** [comment]
Seems like this will probably change as CBA will re-call preInit on mission load in a later verison by the looks of it

**Comment by Sniperhid** [comment]
CBA 3.2.0 -> FIXED: XEH preInit doesn't run when switching terrain in Eden 
@cptnnick - Is this still an issue?

**Comment by cptnnick** [comment]
IIRC yes but cant figure out why.
