### ISSUE TITLE
Admin Menu - Mission Maker's Notes do not support some commands.

### ISSUE THREAD

**Issue by Drofseh** [TMF3/TMF#435]
I am trying to use both the `<execute expression>` and `<marker name>` tags in the admin briefing.
These work correctly when viewing the admin briefing in the briefing itself, but when viewing the admin briefing as the Mission Maker's Notes in the admin menu nothing shows up.

To repo:
1. Try this, works correctly
```sqf
tmf_briefing_admin = "test<br/>test<br/>test";
player createDiaryRecord ["diary", ["Admin", tmf_briefing_admin]];
```
2. Try this, does not work, expected behaviour would be to print True in System Chat
```sqf
testVar = true;
tmf_briefing_admin = "<execute expression='systemChat str testVar'>Test execute expression tag</execute>";
player createDiaryRecord ["diary", ["Admin", tmf_briefing_admin]];
```

**Comment by Drofseh** [comment]
It's possible other tags may or may not work, I haven't tested `<img>` or `<font>` yet.

`<br/>` does work correctly, as shown in the repo steps.

**Comment by Drofseh** [comment]
I think this is probably where it's failing.
https://github.com/TMF3/TMF/blob/0c02703effba0c50a09a8a178ec8e149c0ce590f/addons/adminmenu/functions/fnc_onLoad.sqf#L19

**Comment by Freddo3000** [comment]
Those tags aren't supported by [Structured Text](https://community.bistudio.com/wiki/Structured_Text).

**Comment by beaar** [comment]
^
