### ISSUE TITLE
AI Hunt Vehicle support

### ISSUE THREAD

**Issue by hakkmatt** [TMF3/TMF#7]
AI Hunt doesn't seem to work with modded vehicles if Hunters are set to be -"Synchronized units only".
Tested with RHS BMP-2 (Obr.1980g) (rhs_bmp2e_tv)

**Comment by Sniperhid** [comment]
Fixed in -> https://github.com/TMF3/TMF/commit/61612969ae92b98f27e7cccb7878befa4abd6a32
