### ISSUE TITLE
TMF: General ACRE 2 setting doesnt work correctly

### ISSUE THREAD

**Issue by wexom** [TMF3/TMF#94]
**ACRE2 Terrain Loss** and **ACRE2 Radio Full-duplex** doesnt work. Manual settings in ACRE2 works correctly. Probably because ACRE2 interface change (not sure). I didnt test other TMF/ACRE2 funcionality, only these two.

![image](https://cloud.githubusercontent.com/assets/10631424/23167991/d5f836a6-f846-11e6-8371-dcba994df195.png)

**Comment by Sniperhid** [comment]
Somewhat a duplicate of #69 

This is pending a bit of a re-think of how to best work with the CBA settings overhaul provided in the last stable of ACRE2. I suspect the easiest thing to do is now to remove these settings and let CBA settings handle it.
