### ISSUE TITLE
Creat Task Module "Task Type" does not work

### ISSUE THREAD

**Issue by Jet-12** [TMF3/TMF#95]
There is a box where it should be able to be changed to attack, defend, etc., but nothing happens when it is clicked. I don't know if it is related to TMF or not.

**Comment by Sniperhid** [comment]
Tested with this no mods and loaded and it still occurs. This topic also confirms it's been around for a short while -> https://forums.bistudio.com/topic/199456-create-task-module-after-166wtf/

You can through code change the task type though:
```sqf
//Syntax
[_taskId:string,_taskType:string] call BIS_fnc_taskSetType;
 
//Example
["AttackMike26","attack"] call BIS_fnc_taskSetType;
```

Bit more detail on the task wiki page: https://community.bistudio.com/wiki/Arma_3_Tasks_Overhaul#Task_types
